-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_Test\ise_project_1\alpha4bit2uint8.vhd
-- Created: 2012-11-02 14:15:17
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: alpha4bit2uint8
-- Source Path: test_rx/4bit2uint8
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.test_rx_pkg.ALL;

ENTITY alpha4bit2uint8 IS
  PORT( u                                 :   IN    vector_of_std_logic_vector8(0 TO 3);  -- uint8 [4]
        y                                 :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END alpha4bit2uint8;


ARCHITECTURE rtl OF alpha4bit2uint8 IS

  -- Signals
  SIGNAL u_unsigned                       : vector_of_unsigned8(0 TO 3);  -- uint8 [4]
  SIGNAL y_tmp                            : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  outputgen: FOR k IN 0 TO 3 GENERATE
    u_unsigned(k) <= unsigned(u(k));
  END GENERATE;

  y_tmp <= ((u_unsigned(0) OR (u_unsigned(1) sll 1)) OR (u_unsigned(2) sll 2)) OR (u_unsigned(3) sll 3);

  y <= std_logic_vector(y_tmp);

END rtl;

