-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\ise_project_fpu\alpha8bit2uint8.vhd
-- Created: 2012-12-12 09:55:26
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: alpha8bit2uint8
-- Source Path: contr1/8bit2uint8
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.contr1_pkg.ALL;

ENTITY alpha8bit2uint8 IS
  PORT( u                                 :   IN    vector_of_std_logic_vector8(0 TO 7);  -- uint8 [8]
        y                                 :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END alpha8bit2uint8;


ARCHITECTURE rtl OF alpha8bit2uint8 IS

  -- Signals
  SIGNAL u_unsigned                       : vector_of_unsigned8(0 TO 7);  -- uint8 [8]
  SIGNAL y_tmp                            : unsigned(7 DOWNTO 0);  -- uint8

BEGIN
  outputgen: FOR k IN 0 TO 7 GENERATE
    u_unsigned(k) <= unsigned(u(k));
  END GENERATE;

  y_tmp <= ((((((u_unsigned(7) OR (u_unsigned(6) sll 1)) OR (u_unsigned(5) sll 2)) OR (u_unsigned(4) sll 3)) OR (u_unsigned(3) sll 4)) OR (u_unsigned(2) sll 5)) OR (u_unsigned(1) sll 6)) OR (u_unsigned(0) sll 7);

  y <= std_logic_vector(y_tmp);

END rtl;

