-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\ise_project_fpu\analog_mod_pkg.vhd
-- Created: 2013-02-23 10:31:21
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE analog_mod_pkg IS
  TYPE vector_of_signed12 IS ARRAY (NATURAL RANGE <>) OF signed(11 DOWNTO 0);
  TYPE vector_of_unsigned10 IS ARRAY (NATURAL RANGE <>) OF unsigned(9 DOWNTO 0);
  TYPE vector_of_unsigned11 IS ARRAY (NATURAL RANGE <>) OF unsigned(10 DOWNTO 0);
  TYPE T_state_type_is_DAC_Init IS (IN_AMP_Init, IN_AMP_Init1, IN_DAC_init, IN_End_Init, IN_Led_is_Off, IN_Wait1, IN_Wait10, IN_Wait11, IN_Wait12, IN_Wait13, IN_Wait14, IN_Wait15, IN_Wait16, IN_Wait3, IN_Wait6, IN_Wait7, IN_Wait8, IN_Wait9);
  TYPE T_state_type_is_Handle_Timer_Event IS (IN_AD_Start, IN_Led_is_Off, IN_Led_is_On, IN_Wait1, IN_Wait10, IN_Wait11, IN_Wait12, IN_Wait14, IN_Wait15, IN_Wait17, IN_Wait18, IN_Wait19, IN_Wait20, IN_Wait21, IN_Wait22, IN_Wait23, IN_Wait24, IN_Wait25, IN_Wait3, IN_Wait7, IN_Wait9);
END analog_mod_pkg;

