-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\ise_project_fpu\Embedded_MATLAB_Function.vhd
-- Created: 2013-01-13 16:54:23
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Embedded_MATLAB_Function
-- Source Path: ivedsp/12 bit Program Counter/Embedded MATLAB Function
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Embedded_MATLAB_Function IS
  PORT( u                                 :   IN    std_logic;  -- ufix1
        u1                                :   IN    std_logic;  -- ufix1
        y1                                :   OUT   std_logic_vector(11 DOWNTO 0);  -- ufix12
        y0                                :   OUT   std_logic_vector(11 DOWNTO 0)  -- ufix12
        );
END Embedded_MATLAB_Function;


ARCHITECTURE rtl OF Embedded_MATLAB_Function IS

  -- Signals
  SIGNAL y1_tmp                           : unsigned(11 DOWNTO 0);  -- ufix12
  SIGNAL y0_tmp                           : unsigned(11 DOWNTO 0);  -- ufix12

BEGIN
  y1_tmp <= unsigned'(u & u & u & u & u & u & u & u & u & u & u & u);
  y0_tmp <= unsigned'(u1 & u1 & u1 & u1 & u1 & u1 & u1 & u1 & u1 & u1 & u1 & u1);

  y1 <= std_logic_vector(y1_tmp);

  y0 <= std_logic_vector(y0_tmp);

END rtl;

