-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_Test\ise_project_1\Generator1_pkg.vhd
-- Created: 2012-11-02 14:17:20
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE Generator1_pkg IS
  TYPE T_state_type_is_Gen_Imp IS (IN_Reset, IN_Start, IN_Wait, IN_Wait1, IN_Wait3);
END Generator1_pkg;

