-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_Test\ise_project_1\Generator1.vhd
-- Created: 2012-11-02 14:17:20
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Generator1
-- Source Path: Generator1
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Generator1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        event_r                           :   IN    std_logic;
        send                              :   IN    std_logic;
        ce_out                            :   OUT   std_logic;
        out_event                         :   OUT   std_logic;
        res_tr                            :   OUT   std_logic
        );
END Generator1;


ARCHITECTURE rtl OF Generator1 IS

  -- Component Declarations
  COMPONENT Gen_Imp
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          tx_en                           :   IN    std_logic;
          trig_send                       :   IN    std_logic;
          start_ev                        :   OUT   std_logic;
          res_tr                          :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Gen_Imp
    USE ENTITY work.Gen_Imp(rtl);

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Integer_Delay4_out1              : std_logic;
  SIGNAL Integer_Delay1_out1              : std_logic;
  SIGNAL Gen_Imp_out1                     : std_logic;
  SIGNAL Gen_Imp_out2                     : std_logic;

BEGIN
  u_Gen_Imp : Gen_Imp
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              tx_en => Integer_Delay4_out1,
              trig_send => Integer_Delay1_out1,
              start_ev => Gen_Imp_out1,
              res_tr => Gen_Imp_out2
              );

  enb <= clk_enable;

  Integer_Delay4_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Integer_Delay4_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Integer_Delay4_out1 <= event_r;
      END IF;
    END IF;
  END PROCESS Integer_Delay4_process;


  Integer_Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Integer_Delay1_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Integer_Delay1_out1 <= send;
      END IF;
    END IF;
  END PROCESS Integer_Delay1_process;


  out_event <= Gen_Imp_out1;

  res_tr <= Gen_Imp_out2;

  ce_out <= clk_enable;

END rtl;

