-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\ise_project_fpu\In_Port_Control.vhd
-- Created: 2013-03-14 17:42:03
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: In_Port_Control
-- Source Path: ivedsp/IN_OUT_Controller/In_Port_Control
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY In_Port_Control IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic_vector(4 DOWNTO 0);  -- ufix5
        Enable                            :   IN    std_logic;
        Out1                              :   OUT   std_logic_vector(1 DOWNTO 0)  -- ufix2
        );
END In_Port_Control;


ARCHITECTURE rtl OF In_Port_Control IS

  -- Signals
  SIGNAL Enable_out2                      : std_logic;
  SIGNAL In1_unsigned                     : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Compare_To_Constant6_out1        : std_logic;
  SIGNAL FixPt_Constant6_out1             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Compare_To_Constant5_out1        : std_logic;
  SIGNAL FixPt_Constant5_out1             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Switch6_out1                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL FixPt_Constant4_out1             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Switch5_out1                     : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Switch5_out1_last_value          : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Switch5_out1_bypass              : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  Enable_out2 <= Enable;

  In1_unsigned <= unsigned(In1);

  
  Compare_To_Constant6_out1 <= '1' WHEN In1_unsigned = 11 ELSE
      '0';

  FixPt_Constant6_out1 <= to_unsigned(0, 2);

  
  Compare_To_Constant5_out1 <= '1' WHEN In1_unsigned = 10 ELSE
      '0';

  FixPt_Constant5_out1 <= to_unsigned(2, 2);

  
  Switch6_out1 <= FixPt_Constant6_out1 WHEN Compare_To_Constant6_out1 = '0' ELSE
      FixPt_Constant5_out1;

  FixPt_Constant4_out1 <= to_unsigned(1, 2);

  
  Switch5_out1 <= Switch6_out1 WHEN Compare_To_Constant5_out1 = '0' ELSE
      FixPt_Constant4_out1;

  Out1_bypass_process: PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Switch5_out1_last_value <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF (Enable_out2 AND enb) = '1' THEN
        Switch5_out1_last_value <= Switch5_out1;
      END IF;
    END IF;
  END PROCESS Out1_bypass_process;

  Switch5_out1_bypass <= Switch5_out1 WHEN Enable_out2 = '1' ELSE
                         Switch5_out1_last_value;

  Out1 <= std_logic_vector(Switch5_out1_bypass);

END rtl;

