-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\ise_project_fpu\int2single.vhd
-- Created: 2013-04-30 17:53:18
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: int2single
-- Source Path: int2single
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY int2single IS
  PORT( sig_buf_i                         :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
        sig                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END int2single;


ARCHITECTURE rtl OF int2single IS

  -- Component Declarations
  COMPONENT Int_to_Single1
    PORT( u                               :   IN    std_logic_vector(11 DOWNTO 0);  -- ufix12
          y                               :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Int_to_Single1
    USE ENTITY work.Int_to_Single1(rtl);

  -- Signals
  SIGNAL Int_to_Single1_out1              : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_Int_to_Single1 : Int_to_Single1
    PORT MAP( u => sig_buf_i,  -- ufix12
              y => Int_to_Single1_out1  -- uint32
              );

  sig <= Int_to_Single1_out1;

END rtl;

