-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\ise_project_fpu\MCP4822_SPI_Controller.vhd
-- Created: 2013-04-29 10:18:45
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MCP4822_SPI_Controller
-- Source Path: analog_ext/MCP4822 SPI Controller
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.analog_ext_pkg.ALL;

ENTITY MCP4822_SPI_Controller IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        sample_tick                       :   IN    std_logic;
        CLK_IN                            :   IN    std_logic;
        A                                 :   IN    std_logic_vector(0 TO 15);  -- boolean [16]
        B                                 :   IN    std_logic_vector(0 TO 15);  -- boolean [16]
        CSL                               :   OUT   std_logic;
        CLK_OUT                           :   OUT   std_logic;
        SDI                               :   OUT   std_logic;
        Ready                             :   OUT   std_logic
        );
END MCP4822_SPI_Controller;


ARCHITECTURE rtl OF MCP4822_SPI_Controller IS

  -- Signals
  SIGNAL is_MCP4822_SPI_Controller        : T_state_type_is_MCP4822_SPI_Controller;  -- uint8
  SIGNAL ind                              : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL is_MCP4822_SPI_Controller_next   : T_state_type_is_MCP4822_SPI_Controller;  -- enumerated type (11 enums)
  SIGNAL ind_next                         : unsigned(4 DOWNTO 0);  -- ufix5

BEGIN
  MCP4822_SPI_Controller_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      ind <= to_unsigned(0, 5);
      is_MCP4822_SPI_Controller <= IN_Wait_Request;
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        is_MCP4822_SPI_Controller <= is_MCP4822_SPI_Controller_next;
        ind <= ind_next;
      END IF;
    END IF;
  END PROCESS MCP4822_SPI_Controller_1_process;

  MCP4822_SPI_Controller_1_output : PROCESS (is_MCP4822_SPI_Controller, sample_tick, CLK_IN, A, ind, B)
  BEGIN
    is_MCP4822_SPI_Controller_next <= is_MCP4822_SPI_Controller;
    ind_next <= ind;
    CSL <= '0';
    CLK_OUT <= '0';
    SDI <= '0';
    Ready <= '0';

    CASE is_MCP4822_SPI_Controller IS
      WHEN IN_Buf_state =>
        IF CLK_IN = '1' THEN 
          is_MCP4822_SPI_Controller_next <= IN_Buf_state1;
        END IF;
      WHEN IN_Buf_state1 =>
        IF CLK_IN = '0' THEN 
          CSL <= '0';
          ind_next <= to_unsigned(0, 5);
          SDI <= B(0);
          is_MCP4822_SPI_Controller_next <= IN_DAC_A_Send1;
        END IF;
      WHEN IN_Buf_state2 =>
        IF CLK_IN = '0' THEN 
          Ready <= '0';
          is_MCP4822_SPI_Controller_next <= IN_Buf_state4;
        END IF;
      WHEN IN_Buf_state4 =>
        is_MCP4822_SPI_Controller_next <= IN_Wait_Request;
      WHEN IN_DAC_A_Send =>
        IF CLK_IN = '1' THEN 
          CLK_OUT <= '1';
          ind_next <= ind + 1;
          is_MCP4822_SPI_Controller_next <= IN_Wait_CLK;
        END IF;
      WHEN IN_DAC_A_Send1 =>
        IF CLK_IN = '1' THEN 
          CLK_OUT <= '1';
          ind_next <= ind + 1;
          is_MCP4822_SPI_Controller_next <= IN_Wait_CLK1;
        END IF;
      WHEN IN_LatchData =>
        IF CLK_IN = '1' THEN 
          is_MCP4822_SPI_Controller_next <= IN_Buf_state2;
        END IF;
      WHEN IN_Wait_CLK =>
        IF CLK_IN = '0' THEN 
          IF ind = 16 THEN 
            CLK_OUT <= '0';
            CSL <= '1';
            is_MCP4822_SPI_Controller_next <= IN_Buf_state;
          ELSE 
            CLK_OUT <= '0';
            SDI <= A(to_integer(ind));
            is_MCP4822_SPI_Controller_next <= IN_DAC_A_Send;
          END IF;
        END IF;
      WHEN IN_Wait_CLK1 =>
        IF CLK_IN = '0' THEN 
          IF ind = 16 THEN 
            CLK_OUT <= '0';
            CSL <= '1';
            is_MCP4822_SPI_Controller_next <= IN_LatchData;
          ELSE 
            CLK_OUT <= '0';
            SDI <= B(to_integer(ind));
            is_MCP4822_SPI_Controller_next <= IN_DAC_A_Send1;
          END IF;
        END IF;
      WHEN IN_Wait_CLK_0 =>
        IF CLK_IN = '0' THEN 
          CSL <= '0';
          CLK_OUT <= '0';
          ind_next <= to_unsigned(0, 5);
          SDI <= A(0);
          is_MCP4822_SPI_Controller_next <= IN_DAC_A_Send;
        END IF;
      WHEN IN_Wait_Request =>
        IF sample_tick = '1' THEN 
          Ready <= '1';
          is_MCP4822_SPI_Controller_next <= IN_Wait_CLK_0;
        END IF;
      WHEN OTHERS => 
        CSL <= '1';
        CLK_OUT <= '0';
        SDI <= '0';
        Ready <= '0';
        is_MCP4822_SPI_Controller_next <= IN_Wait_Request;
    END CASE;

  END PROCESS MCP4822_SPI_Controller_1_output;


END rtl;

