-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\ise_project_fpu\programmer_pkg.vhd
-- Created: 2013-02-09 16:56:18
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE programmer_pkg IS
  TYPE vector_of_std_logic_vector8 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(7 DOWNTO 0);
  TYPE vector_of_unsigned8 IS ARRAY (NATURAL RANGE <>) OF unsigned(7 DOWNTO 0);
  TYPE T_state_type_is_Programmer IS (IN_Data, IN_Data1, IN_Data2, IN_Data3, IN_End, IN_End1, IN_Ready, IN_Ready1, IN_Request, IN_Start, IN_Wait, IN_Wait1);
END programmer_pkg;

