-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\ise_project_fpu\Rise_detect1.vhd
-- Created: 2013-03-14 17:42:03
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Rise_detect1
-- Source Path: ivedsp/IN_OUT_Controller/Rise_detect1
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Rise_detect1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        In1                               :   IN    std_logic;
        Out1                              :   OUT   std_logic
        );
END Rise_detect1;


ARCHITECTURE rtl OF Rise_detect1 IS

  -- Signals
  SIGNAL BRAM3_out1                       : std_logic;
  SIGNAL BRAM3_out1_1                     : std_logic;
  SIGNAL Logical_Operator6_out1           : std_logic;

BEGIN
  BRAM3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      BRAM3_out1 <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        BRAM3_out1 <= In1;
      END IF;
    END IF;
  END PROCESS BRAM3_process;


  BRAM3_out1_1 <=  NOT BRAM3_out1;

  Logical_Operator6_out1 <= BRAM3_out1_1 AND In1;

  Out1 <= Logical_Operator6_out1;

END rtl;

