-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_Test\ise_project_1\Roll_speed_compensator.vhd
-- Created: 2012-11-05 22:45:21
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Roll_speed_compensator
-- Source Path: ss_controller/Roll speed compensator
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ss_controller_pkg.ALL;

ENTITY Roll_speed_compensator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Tick                              :   IN    std_logic;
        u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En20
        );
END Roll_speed_compensator;


ARCHITECTURE rtl OF Roll_speed_compensator IS

  -- Component Declarations
  COMPONENT MAC_instruction_block1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          mul1                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
          mul2                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
          reset_1                         :   IN    std_logic;
          result                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En20
          );
  END COMPONENT;

  COMPONENT MAC_instruction_Controller1_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          sys                             :   IN    vector_of_std_logic_vector32(0 TO 2);  -- sfix32_En20 [3]
          xu                              :   IN    vector_of_std_logic_vector32(0 TO 2);  -- sfix32_En20 [3]
          result                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
          Model_Tick                      :   IN    std_logic;
          mul1                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
          mul2                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En20
          reset_1                         :   OUT   std_logic;
          xy                              :   OUT   vector_of_std_logic_vector32(0 TO 1)  -- sfix32_En20 [2]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : MAC_instruction_block1
    USE ENTITY work.MAC_instruction_block1(rtl);

  FOR ALL : MAC_instruction_Controller1_block
    USE ENTITY work.MAC_instruction_Controller1_block(rtl);

  -- Signals
  SIGNAL Parameters_out1                  : vector_of_signed32(0 TO 2);  -- sfix32_En20 [3]
  SIGNAL Parameters_out1_1                : vector_of_std_logic_vector32(0 TO 2);  -- ufix32 [3]
  SIGNAL MAC_instruction_Controller1_out1 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL MAC_instruction_Controller1_out2 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL MAC_instruction_Controller1_out3 : std_logic;
  SIGNAL MAC_instruction_out1             : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL MAC_instruction_Controller1_out4 : vector_of_std_logic_vector32(0 TO 1);  -- ufix32 [2]
  SIGNAL MAC_instruction_Controller1_out4_1 : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL u_old_out1                       : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL MAC_instruction_Controller1_out4_0 : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL y_old_out1                       : signed(31 DOWNTO 0);  -- sfix32_En20
  SIGNAL Mux_out1                         : vector_of_signed32(0 TO 2);  -- sfix32_En20 [3]
  SIGNAL Mux_out1_1                       : vector_of_std_logic_vector32(0 TO 2);  -- ufix32 [3]

BEGIN
  -- Relizaciq na diskretna predavatelna
  -- funkciq ot vida: W=k0(z-a)/(z-b).
  -- 
  -- Izhoda v momenta k se izchislqva po formulata:
  -- y(k)=by(k-1)+k0u(k)-k0au(k-1)

  u_MAC_instruction : MAC_instruction_block1
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              mul1 => MAC_instruction_Controller1_out1,  -- sfix32_En20
              mul2 => MAC_instruction_Controller1_out2,  -- sfix32_En20
              reset_1 => MAC_instruction_Controller1_out3,
              result => MAC_instruction_out1  -- sfix32_En20
              );

  u_MAC_instruction_Controller1 : MAC_instruction_Controller1_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              sys => Parameters_out1_1,  -- sfix32_En20 [3]
              xu => Mux_out1_1,  -- sfix32_En20 [3]
              result => MAC_instruction_out1,  -- sfix32_En20
              Model_Tick => Tick,
              mul1 => MAC_instruction_Controller1_out1,  -- sfix32_En20
              mul2 => MAC_instruction_Controller1_out2,  -- sfix32_En20
              reset_1 => MAC_instruction_Controller1_out3,
              xy => MAC_instruction_Controller1_out4  -- sfix32_En20 [2]
              );

  Parameters_out1(0) <= to_signed(1048576, 32);
  Parameters_out1(1) <= to_signed(1049, 32);
  Parameters_out1(2) <= to_signed(-1038, 32);

  outputgen1: FOR k IN 0 TO 2 GENERATE
    Parameters_out1_1(k) <= std_logic_vector(Parameters_out1(k));
  END GENERATE;

  MAC_instruction_Controller1_out4_1 <= signed(MAC_instruction_Controller1_out4(1));

  u_old_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      u_old_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        u_old_out1 <= MAC_instruction_Controller1_out4_1;
      END IF;
    END IF;
  END PROCESS u_old_process;


  MAC_instruction_Controller1_out4_0 <= signed(MAC_instruction_Controller1_out4(0));

  y_old_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      y_old_out1 <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        y_old_out1 <= MAC_instruction_Controller1_out4_0;
      END IF;
    END IF;
  END PROCESS y_old_process;


  Mux_out1(0) <= y_old_out1;
  Mux_out1(1) <= signed(u);
  Mux_out1(2) <= u_old_out1;

  outputgen: FOR k IN 0 TO 2 GENERATE
    Mux_out1_1(k) <= std_logic_vector(Mux_out1(k));
  END GENERATE;

  y <= MAC_instruction_Controller1_out4(0);

END rtl;

