-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_Test\ise_project_1\ss_controller_pkg.vhd
-- Created: 2012-11-05 22:45:21
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE ss_controller_pkg IS
  TYPE vector_of_std_logic_vector32 IS ARRAY (NATURAL RANGE <>) OF std_logic_vector(31 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
  TYPE T_state_type_is_MAC_instruction_Controller11 IS (IN_calc1, IN_calc2, IN_calc3, IN_calc4, IN_calc5, IN_resetw, IN_wait_f, IN_wait_r);
  TYPE T_state_type_is_MAC_instruction_Controller1 IS (IN_calc1, IN_calc2, IN_calc3, IN_resetw, IN_wait_f, IN_wait_r);
END ss_controller_pkg;

