vlib work
vcom  ss_controller_pkg.vhd
vcom  MAC_instruction.vhd
vcom  MAC_instruction_Controller1.vhd
vcom  Forward_speed_tracking.vhd
vcom  MAC_instruction_block.vhd
vcom  MAC_instruction_Controller1_block.vhd
vcom  Pitch_speed_compensator.vhd
vcom  MAC_instruction_block1.vhd
vcom  Roll_speed_compensator.vhd
vcom  MAC_instruction_block2.vhd
vcom  Side_speed_tracking.vhd
vcom  MAC_instruction_block3.vhd
vcom  Vectical_speed_tracking.vhd
vcom  MAC_instruction_block4.vhd
vcom  Yaw_speed.vhd
vcom  ss_controller.vhd
