-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\fp_gen\fp_sum_pkg.vhd
-- Created: 2013-02-05 22:38:03
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE fp_sum_pkg IS
  TYPE vector_of_signed9 IS ARRAY (NATURAL RANGE <>) OF signed(8 DOWNTO 0);
  TYPE vector_of_signed32 IS ARRAY (NATURAL RANGE <>) OF signed(31 DOWNTO 0);
END fp_sum_pkg;

