-- -------------------------------------------------------------
-- 
-- File Name: D:\Dan\FPGA_FPU\fp_gen\Variable_bitshift.vhd
-- Created: 2013-02-05 22:38:03
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Variable_bitshift
-- Source Path: fp_sum/Variable bitshift
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Variable_bitshift IS
  PORT( u                                 :   IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        n                                 :   IN    std_logic_vector(7 DOWNTO 0);  -- int8
        y                                 :   OUT   std_logic_vector(31 DOWNTO 0)  -- uint32
        );
END Variable_bitshift;


ARCHITECTURE rtl OF Variable_bitshift IS

  -- Signals
  SIGNAL u_unsigned                       : unsigned(31 DOWNTO 0);  -- uint32
  SIGNAL n_signed                         : signed(7 DOWNTO 0);  -- int8
  SIGNAL y_tmp                            : unsigned(31 DOWNTO 0);  -- uint32

BEGIN
  u_unsigned <= unsigned(u);

  n_signed <= signed(n);

  Variable_bitshift_1_output : PROCESS (u_unsigned, n_signed)
    VARIABLE k : signed(7 DOWNTO 0);
    VARIABLE absk1 : unsigned(7 DOWNTO 0);
    VARIABLE absk1_0 : unsigned(7 DOWNTO 0);
    VARIABLE t_0 : signed(8 DOWNTO 0);
    VARIABLE k_0 : signed(8 DOWNTO 0);
    VARIABLE cast : signed(7 DOWNTO 0);
  BEGIN
    t_0 :=  - (resize(n_signed, 9));
    IF (t_0(8) = '0') AND (t_0(7) /= '0') THEN 
      k := "01111111";
    ELSIF (t_0(8) = '1') AND (t_0(7) /= '1') THEN 
      k := "10000000";
    ELSE 
      k := t_0(7 DOWNTO 0);
    END IF;
    y_tmp <= to_unsigned(0, 32);
    IF k < 0 THEN 
      k_0 :=  - (resize(k, 9));
      IF (k_0(8) = '0') AND (k_0(7) /= '0') THEN 
        cast := "01111111";
      ELSIF (k_0(8) = '1') AND (k_0(7) /= '1') THEN 
        cast := "10000000";
      ELSE 
        cast := k_0(7 DOWNTO 0);
      END IF;
      IF cast(7) = '1' THEN 
        absk1_0 := "00000000";
      ELSE 
        absk1_0 := unsigned(cast);
      END IF;
      IF absk1_0 < 32 THEN 
        y_tmp <= u_unsigned srl to_integer(absk1_0);
      END IF;
    ELSE 
      absk1 := unsigned(k);
      IF absk1 < 32 THEN 
        y_tmp <= u_unsigned sll to_integer(absk1);
      END IF;
    END IF;
  END PROCESS Variable_bitshift_1_output;


  y <= std_logic_vector(y_tmp);

END rtl;

